name: Bug Report
description: Report a bug in Smart Pantry
title: "[Bug] "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Provide a concise description of the issue.
      placeholder: The bug occurs when...
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detail the steps to reproduce the issue.
      placeholder: |
        1. Go to...
        2. Click...
        3. Observe...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: Describe what actually happened.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context (logs, screenshots, environment info).
