name: Feature Request
description: Suggest an idea for Smart Pantry
title: "[Feature] "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature to improve Smart Pantry.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Provide a concise description of the feature.
      placeholder: I'd like Smart Pantry to...
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Explain why this feature is important.
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Proposed Solution
      description: Describe how you imagine the feature working.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: List any alternative solutions or features you have considered.
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context (mockups, references, related issues).
